// Türkiye'nin tüm illeri ve bazı büyük ilçeler
const allCities = [
  'Adana',
  'Adıyaman',
  'Afyonkarahisar',
  'Ağrı',
  'Amasya',
  'Ankara',
  'Antalya',
  'Artvin',
  'Aydın',
  'Balıkesir',
  'Bilecik',
  'Bingöl',
  'Bitlis',
  'Bolu',
  'Burdur',
  'Bursa',
  'Çanakkale',
  'Çankırı',
  'Çorum',
  'Denizli',
  'Diyarbakır',
  'Edirne',
  'Elazığ',
  'Erzincan',
  'Erzurum',
  'Eskişehir',
  'Gaziantep',
  'Giresun',
  'Gümüşhane',
  'Hakkâri',
  'Hatay',
  'Isparta',
  'Mersin',
  'İstanbul',
  'İzmir',
  'Kars',
  'Kastamonu',
  'Kayseri',
  'Kırklareli',
  'Kırşehir',
  'Kocaeli',
  'Konya',
  'Kütahya',
  'Malatya',
  'Manisa',
  'Kahramanmaraş',
  'Mardin',
  'Muğla',
  'Muş',
  'Nevşehir',
  'Niğde',
  'Ordu',
  'Rize',
  'Sakarya',
  'Samsun',
  'Siirt',
  'Sinop',
  'Sivas',
  'Tekirdağ',
  'Tokat',
  'Trabzon',
  'Tunceli',
  'Şanlıurfa',
  'Uşak',
  'Van',
  'Yozgat',
  'Zonguldak',
  'Aksaray',
  'Bayburt',
  'Karaman',
  'Kırıkkale',
  'Batman',
  'Şırnak',
  'Bartın',
  'Ardahan',
  'Iğdır',
  'Yalova',
  'Karabük',
  'Kilis',
  'Osmaniye',
  'Düzce',
  // Büyük ilçeler ve semtler
  'Kadıköy',
  'Beşiktaş',
  'Şişli',
  'Fatih',
  'Üsküdar',
  'Beyoğlu',
  'Bakırköy',
  'Maltepe',
  'Pendik',
  'Kartal',
  'Tuzla',
  'Sultanbeyli',
  'Sancaktepe',
  'Çekmeköy',
  'Ümraniye',
  'Ataşehir',
  'Sultangazi',
  'Esenler',
  'Bağcılar',
  'Küçükçekmece',
  'Büyükçekmece',
  'Avcılar',
  'Zeytinburnu',
  'Bayrampaşa',
  'Güngören',
  'Bahçelievler',
  'Başakşehir',
  'Arnavutköy',
  'Sultangazi',
  'Esenyurt',
  'Beylikdüzü',
  'Çatalca',
  'Silivri',
  'Şile',
  'Adalar',
  'Konak',
  'Bornova',
  'Karşıyaka',
  'Çiğli',
  'Balçova',
  'Narlıdere',
  'Güzelbahçe',
  'Urla',
  'Seferihisar',
  'Menderes',
  'Gaziemir',
  'Buca',
  'Torbalı',
  'Kemalpaşa',
  'Menemen',
  'Aliağa',
  'Foça',
  'Bergama',
  'Dikili',
  'Kınık',
  'Tire',
  'Bayındır',
  'Kiraz',
  'Ödemiş',
  'Beydağ',
  'Torbali',
  'Selçuk',
  'Germencik',
  'İncirliova',
  'Kuyucak',
  'Bozdoğan',
  'Karacasu',
  'Sultanhisar',
  'Köşk',
  'Yenipazar',
  'Karpuzlu',
  'Çine',
  'Köyceğiz',
  'Datça',
  'Marmaris',
  'Bodrum',
  'Milas',
  'Yatağan',
  'Ula',
  'Menteşe',
  'Fethiye',
  'Kaş',
  'Kalkan',
  'Demre',
  'Korkuteli',
  'Elmalı',
  'Finike',
  'Kumluca',
  'Manavgat',
  'Serik',
  'Akseki',
  'İbradı',
  'Gündoğmuş',
  'Kepez',
  'Muratpaşa',
  'Konyaaltı',
  'Döşemealtı',
  'Aksu',
  'Korkuteli',
  'Elmalı',
  'Finike',
  'Kumluca',
  'Manavgat',
  'Serik',
  'Akseki',
  'İbradı',
  'Gündoğmuş',
  'Nilüfer',
  'Osmangazi',
  'Yıldırım',
  'İnegöl',
  'Gemlik',
  'Mudanya',
  'Gürsu',
  'Harmancık',
  'Keles',
  'Orhaneli',
  'Orhangazi',
  'Yenişehir',
  'İznik',
  'Karacabey',
  'Mustafakemalpaşa',
  'Mudanya',
  'Gürsu',
  'Harmancık',
  'Keles',
  'Orhaneli',
  'Orhangazi',
  'Yenişehir',
  'İznik',
  'Karacabey',
  'Mustafakemalpaşa',
  'Altınova',
  'Armutlu',
  'Çınarcık',
  'Çiftlikköy',
  'Termal'
]

// Duplikate entfernen und exportieren
export const turkishCities = [...new Set(allCities)]

export const getCitySuggestions = (query: string, limit: number = 10): string[] => {
  if (!query || query.length < 1) return []
  
  const lowercaseQuery = query.toLowerCase()
  
  return turkishCities
    .filter(city => 
      city.toLowerCase().includes(lowercaseQuery) ||
      city.toLowerCase().startsWith(lowercaseQuery)
    )
    .sort((a, b) => {
      // Önce başlayanları, sonra içerenleri sırala
      const aStartsWith = a.toLowerCase().startsWith(lowercaseQuery)
      const bStartsWith = b.toLowerCase().startsWith(lowercaseQuery)
      
      if (aStartsWith && !bStartsWith) return -1
      if (!aStartsWith && bStartsWith) return 1
      
      return a.localeCompare(b, 'tr')
    })
    .slice(0, limit)
}
